apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque                      # for contents of this Secret as unstructured or key-value pair format like db-username: rahul etc
data:
  db-password: xxxxxx   # Output of echo -n 'dbpassword11' | base64
